- name: 'bug'
  color: 'd73a4a'
  description: 'Something isn\'t working'
- name: 'bugfix'
  color: 'd73a4a'
  description: 'Pull requests that fix some issues'
- name: 'chore'
  color: 'ffffff'
- name: 'ci'
  color: '1d76db'
- name: 'dependencies'
  color: '0366d6'
  description: 'Pull requests that update a dependency file'
- name: 'feature request'
  color: 'fcf95a'
- name: 'good first issue'
  color: '7057ff'
  description: 'Good for newcomers'
- name: 'help wanted'
  color: '008672'
  description: 'Need help solving an issue'
- name: 'need repro'
  color: '0e8a16'
  description: 'More information is needed'
- name: 'priority: high'
  color: 'b60205'
- name: 's: duplicate'
  color: '91a1f5'
- name: 's: invalid'
  color: '91a1f5'
- name: 's: won\'t fix'
  color: '91a1f5'
- name: 'slash commands'
  color: '99dc3e'
- name: 'type: feature'
  color: 'fcf95a'
- name: 'type: discord'
  color: '5663e9'
- name: 'type: discord.js'
  color: '0b8d92'
- name: 'typings'
  color: '80c042'