name: Test
on: [push, pull_request]
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.16.0, 18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
        
      - name: Install Dependencies
        run: yarn --immutable

      - name: Run Lint
        run: yarn lint

      - name: Run TypeScript Compiler
        run: yarn build